### ISSUE TITLE
Peer feedback

### ISSUE THREAD

**Issue by theBwoyProgrammer** [tarek102/To-Do-List-Peer-Feedback#2]
Hi @tarek102,

I am thrilled to share with you the excellent news that your use of JavaScript demonstrates exceptional adherence to industry-recommended best practices. Your attention to detail and commitment to quality are greatly appreciated

**Comment by theBwoyProgrammer** [comment]
Hey @tarek102, 

- Kindly consider linking your script files to your HTML file because it is essential for adding interactivity and functionality to your web page.

- Please consider fixing the extra border around your `Add to your list` placeholder so that the UI can look clean and attractive enough.

![image](https://user-images.githubusercontent.com/102610715/231124058-449da2aa-5128-43a0-9d5e-ec4b8728340a.png)

- Kindly remove the `<h3>Today's To Do</h3>` from the `li` tags because the `h3` in this case isn't a list so, it can be placed outside the `ul` tags

**Comment by HatimDev-HE** [comment]
@tarek102 I afterwards saw the closed PR
